// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SPMS_Backend.Data;

#nullable disable

namespace SPMS_Backend.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("SPMS_Backend.Models.ProjectGroup", b =>
                {
                    b.Property<int>("ProjectGroupID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("ProjectGroupID"));

                    b.Property<double>("AverageCPI")
                        .HasColumnType("double");

                    b.Property<int?>("ConvenerStaffID")
                        .HasColumnType("int");

                    b.Property<DateTime>("Created")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Description")
                        .HasColumnType("longtext");

                    b.Property<int?>("ExpertStaffID")
                        .HasColumnType("int");

                    b.Property<int>("GuideStaffID")
                        .HasColumnType("int");

                    b.Property<DateTime>("Modified")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("ProjectArea")
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<string>("ProjectDescription")
                        .HasColumnType("longtext");

                    b.Property<string>("ProjectGroupName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<string>("ProjectTitle")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<int>("ProjectTypeID")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("StatusDescription")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.HasKey("ProjectGroupID");

                    b.HasIndex("ConvenerStaffID");

                    b.HasIndex("ExpertStaffID");

                    b.HasIndex("GuideStaffID");

                    b.HasIndex("ProjectTypeID");

                    b.ToTable("ProjectGroups");
                });

            modelBuilder.Entity("SPMS_Backend.Models.ProjectGroupMember", b =>
                {
                    b.Property<int>("ProjectGroupMemberID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("ProjectGroupMemberID"));

                    b.Property<DateTime>("Created")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<bool>("IsGroupLeader")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTime>("Modified")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("ProjectGroupID")
                        .HasColumnType("int");

                    b.Property<double>("StudentCGPA")
                        .HasColumnType("double");

                    b.Property<int>("StudentID")
                        .HasColumnType("int");

                    b.HasKey("ProjectGroupMemberID");

                    b.HasIndex("ProjectGroupID");

                    b.HasIndex("StudentID");

                    b.ToTable("ProjectGroupMembers");
                });

            modelBuilder.Entity("SPMS_Backend.Models.ProjectMeeting", b =>
                {
                    b.Property<int>("ProjectMeetingID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("ProjectMeetingID"));

                    b.Property<DateTime>("Created")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("GuideStaffID")
                        .HasColumnType("int");

                    b.Property<DateTime>("MeetingDateTime")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("MeetingLocation")
                        .HasMaxLength(300)
                        .HasColumnType("varchar(300)");

                    b.Property<string>("MeetingNotes")
                        .HasColumnType("longtext");

                    b.Property<string>("MeetingPurpose")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<string>("MeetingStatus")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<DateTime>("Modified")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("ProjectGroupID")
                        .HasColumnType("int");

                    b.Property<string>("StatusDescription")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.HasKey("ProjectMeetingID");

                    b.HasIndex("GuideStaffID");

                    b.HasIndex("ProjectGroupID");

                    b.ToTable("ProjectMeetings");
                });

            modelBuilder.Entity("SPMS_Backend.Models.ProjectMeetingAttendance", b =>
                {
                    b.Property<int>("ProjectMeetingAttendanceID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("ProjectMeetingAttendanceID"));

                    b.Property<string>("AttendanceRemarks")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<DateTime>("Created")
                        .HasColumnType("datetime(6)");

                    b.Property<bool>("IsPresent")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTime>("Modified")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("ProjectMeetingID")
                        .HasColumnType("int");

                    b.Property<int>("StudentID")
                        .HasColumnType("int");

                    b.HasKey("ProjectMeetingAttendanceID");

                    b.HasIndex("ProjectMeetingID");

                    b.HasIndex("StudentID");

                    b.ToTable("ProjectMeetingAttendances");
                });

            modelBuilder.Entity("SPMS_Backend.Models.ProjectType", b =>
                {
                    b.Property<int>("ProjectTypeID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("ProjectTypeID"));

                    b.Property<DateTime>("Created")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<DateTime>("Modified")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("ProjectTypeName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.HasKey("ProjectTypeID");

                    b.ToTable("ProjectTypes");

                    b.HasData(
                        new
                        {
                            ProjectTypeID = 1,
                            Created = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Final year major project",
                            Modified = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            ProjectTypeName = "Major Project"
                        },
                        new
                        {
                            ProjectTypeID = 2,
                            Created = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Semester mini project",
                            Modified = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            ProjectTypeName = "Mini Project"
                        },
                        new
                        {
                            ProjectTypeID = 3,
                            Created = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Research and development project",
                            Modified = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            ProjectTypeName = "Research Project"
                        });
                });

            modelBuilder.Entity("SPMS_Backend.Models.Staff", b =>
                {
                    b.Property<int>("StaffID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("StaffID"));

                    b.Property<DateTime>("Created")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<DateTime>("Modified")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Phone")
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("StaffName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.HasKey("StaffID");

                    b.ToTable("Staffs");

                    b.HasData(
                        new
                        {
                            StaffID = 1,
                            Created = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "System Administrator",
                            Email = "admin@university.edu",
                            Modified = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Password = "$2a$11$airwSniyUxb0sjl7AyXP1O/Qk1KxZR0kWl9o6hUiAhjvtACZ1WFk2",
                            Phone = "9000000000",
                            Role = "Admin",
                            StaffName = "Admin User"
                        },
                        new
                        {
                            StaffID = 2,
                            Created = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Professor - Computer Science",
                            Email = "rajesh.kumar@university.edu",
                            Modified = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Password = "$2a$11$COOaUMgbp/RgYVV7xGB1huDnDM2./zY4YWRKdVhyRWgbJX6L1H5nW",
                            Phone = "9876543210",
                            Role = "Faculty",
                            StaffName = "Dr. Rajesh Kumar"
                        },
                        new
                        {
                            StaffID = 3,
                            Created = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Associate Professor - AI/ML",
                            Email = "priya.sharma@university.edu",
                            Modified = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Password = "$2a$11$ZpCqjArPwXdM/JlZV7KgNOOkNbik2XBTq8j7PXwuKshOULflvnXDm",
                            Phone = "9876543211",
                            Role = "Faculty",
                            StaffName = "Dr. Priya Sharma"
                        });
                });

            modelBuilder.Entity("SPMS_Backend.Models.Student", b =>
                {
                    b.Property<int>("StudentID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("StudentID"));

                    b.Property<double>("CGPA")
                        .HasColumnType("double");

                    b.Property<DateTime>("Created")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<DateTime>("Modified")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Phone")
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.Property<string>("StudentName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.HasKey("StudentID");

                    b.ToTable("Students");

                    b.HasData(
                        new
                        {
                            StudentID = 1,
                            CGPA = 8.5,
                            Created = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "CSE - 4th Year",
                            Email = "arjun.m@student.edu",
                            Modified = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Password = "$2a$11$CWyyveP7Jy8Zkup24N4gSO9c8h/Ny8LwqojDTzsinyFcsT6IPlgy.",
                            Phone = "9123456780",
                            StudentName = "Arjun Mehta"
                        },
                        new
                        {
                            StudentID = 2,
                            CGPA = 9.0999999999999996,
                            Created = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "CSE - 4th Year",
                            Email = "sneha.r@student.edu",
                            Modified = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Password = "$2a$11$jYvoqYVATSy4pFXdxn4WtedXLytg95oQXm0aps8Wks3VADRN3rK8e",
                            Phone = "9123456781",
                            StudentName = "Sneha Reddy"
                        },
                        new
                        {
                            StudentID = 3,
                            CGPA = 8.8000000000000007,
                            Created = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "CSE - 4th Year",
                            Email = "vikram.s@student.edu",
                            Modified = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Password = "$2a$11$yKgpijlKWrr29OkwpioMcO2kjR2BTRqNVOjUMaWwcOGBKAEIl4zWe",
                            Phone = "9123456782",
                            StudentName = "Vikram Singh"
                        },
                        new
                        {
                            StudentID = 4,
                            CGPA = 9.3000000000000007,
                            Created = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "CSE - 4th Year",
                            Email = "ananya.g@student.edu",
                            Modified = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Password = "$2a$11$fQEK6vKg6Lndr/hhJPH63OD7kLDvIFFimWIEWqpp69biNlyI3MmC6",
                            Phone = "9123456783",
                            StudentName = "Ananya Gupta"
                        },
                        new
                        {
                            StudentID = 5,
                            CGPA = 8.1999999999999993,
                            Created = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "CSE - 3rd Year",
                            Email = "rohan.j@student.edu",
                            Modified = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Password = "$2a$11$BU92mm8qbFg4V2WPF/LI9Oh1M0rpKXf0PHSz2LTZSYNO0.mSBtyJ6",
                            Phone = "9123456784",
                            StudentName = "Rohan Joshi"
                        },
                        new
                        {
                            StudentID = 6,
                            CGPA = 8.9000000000000004,
                            Created = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "CSE - 3rd Year",
                            Email = "kavya.n@student.edu",
                            Modified = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Password = "$2a$11$ZZ.zGhrw40E73nEVKoUJieNETO6vihKmmRmhbYBnIPtoWvyrcnd9K",
                            Phone = "9123456785",
                            StudentName = "Kavya Nair"
                        });
                });

            modelBuilder.Entity("SPMS_Backend.Models.ProjectGroup", b =>
                {
                    b.HasOne("SPMS_Backend.Models.Staff", "ConvenerStaff")
                        .WithMany()
                        .HasForeignKey("ConvenerStaffID")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("SPMS_Backend.Models.Staff", "ExpertStaff")
                        .WithMany()
                        .HasForeignKey("ExpertStaffID")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("SPMS_Backend.Models.Staff", "GuideStaff")
                        .WithMany()
                        .HasForeignKey("GuideStaffID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SPMS_Backend.Models.ProjectType", "ProjectType")
                        .WithMany()
                        .HasForeignKey("ProjectTypeID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ConvenerStaff");

                    b.Navigation("ExpertStaff");

                    b.Navigation("GuideStaff");

                    b.Navigation("ProjectType");
                });

            modelBuilder.Entity("SPMS_Backend.Models.ProjectGroupMember", b =>
                {
                    b.HasOne("SPMS_Backend.Models.ProjectGroup", "ProjectGroup")
                        .WithMany("Members")
                        .HasForeignKey("ProjectGroupID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SPMS_Backend.Models.Student", "Student")
                        .WithMany()
                        .HasForeignKey("StudentID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ProjectGroup");

                    b.Navigation("Student");
                });

            modelBuilder.Entity("SPMS_Backend.Models.ProjectMeeting", b =>
                {
                    b.HasOne("SPMS_Backend.Models.Staff", "GuideStaff")
                        .WithMany()
                        .HasForeignKey("GuideStaffID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SPMS_Backend.Models.ProjectGroup", "ProjectGroup")
                        .WithMany()
                        .HasForeignKey("ProjectGroupID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("GuideStaff");

                    b.Navigation("ProjectGroup");
                });

            modelBuilder.Entity("SPMS_Backend.Models.ProjectMeetingAttendance", b =>
                {
                    b.HasOne("SPMS_Backend.Models.ProjectMeeting", "ProjectMeeting")
                        .WithMany("Attendances")
                        .HasForeignKey("ProjectMeetingID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SPMS_Backend.Models.Student", "Student")
                        .WithMany()
                        .HasForeignKey("StudentID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ProjectMeeting");

                    b.Navigation("Student");
                });

            modelBuilder.Entity("SPMS_Backend.Models.ProjectGroup", b =>
                {
                    b.Navigation("Members");
                });

            modelBuilder.Entity("SPMS_Backend.Models.ProjectMeeting", b =>
                {
                    b.Navigation("Attendances");
                });
#pragma warning restore 612, 618
        }
    }
}
